/**:
  ros__parameters:
    simulated_frame_id: "base_link"
    origin_frame_id: "map"
    vehicle_model_type: "DELAY_STEER_ACC_GEARED"
    initialize_source: "INITIAL_POSE_TOPIC"
    timer_sampling_time_ms: 25
    add_measurement_noise: False
    vel_lim: 50.0
    vel_rate_lim: 7.0
    steer_lim: 1.0
    steer_rate_lim: 5.0
    acc_time_delay: 0.1
    acc_time_constant: 0.1
    steer_time_delay: 0.24
    steer_time_constant: 0.27
    x_stddev: 0.0001 # x standard deviation for dummy covariance in map coordinate
    y_stddev: 0.0001 # y standard deviation for dummy covariance in map coordinate
